### ISSUE TITLE
readme里的qq群搜索不到

### ISSUE THREAD

**Issue by kagangtuya-star** [pear-studio/nonebot-dicepp#1]
![](https://gitee.com/kagangtuya_light/picbed/raw/master/img/20210830113830.png)
**群没了**

**Comment by pear-studio** [comment]
群被TX神隐了, 解不开, 用二维码加, 或者加我好友吧
![微信图片_20210830133228](https://user-images.githubusercontent.com/88259371/131290002-0600bab7-0fdc-4b9f-b1f7-54e22fdf1be6.jpg)
